name: Orbiter API tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ipa-nodejs:
    name: Node tests
    runs-on: ubuntu-latest
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm test:node

      - name: Envoyer couverture à Codecov
        uses: codecov/codecov-action@v4
  
  test-ipa-navig:
    name: Browser tests
    runs-on: ubuntu-latest
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        run: pnpm test:browser

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v4

  test-ipa-electron-principal:
    name: Electron main tests
    needs: test-ipa-nodejs
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.1.0"
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Installer playwright
        run: npx playwright install

      - name: Vérifier les tests
        # De cawa-93/vite-electron-builder
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm run test:electron-main
        if: matrix.os == 'ubuntu-latest'

      - run: pnpm run test:electron-main
        if: matrix.os != 'ubuntu-latest'

      - name: Envoyer couverture à Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
